import Head from "next/head";
import Image from "next/image";
import StartPage from "../src/startpage/StartPage";
import styles from "../styles/Home.module.css";

export default function Home({
  wasteCountTypeThisYear,
  wasteThisYear,
  wasteCountCurrentMonth,
  wasteCountCurrentMonthType,
  servicecountCurrentYear,
  servicecountCurrentYearType,
  serviceCountCurrentMonth,
  serviceCountCurrentMonthType,
  newbladesCount,
  newbladesCountType,
  newbladesCountCurrentMonth,
  newBladesCurrentMonthType,
  setInput,
  searchResult,
  openSearchResults,
  setOpenSearchResults,
  input,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moelven Våler | Verktøyregister</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StartPage
        wasteCountTypeThisYear={wasteCountTypeThisYear}
        wasteThisYear={wasteThisYear}
        wasteCountCurrentMonth={wasteCountCurrentMonth}
        wasteCountCurrentMonthType={wasteCountCurrentMonthType}
        servicecountCurrentYear={servicecountCurrentYear}
        servicecountCurrentYearType={servicecountCurrentYearType}
        serviceCountCurrentMonth={serviceCountCurrentMonth}
        serviceCountCurrentMonthType={serviceCountCurrentMonthType}
        newbladesCount={newbladesCount}
        newbladesCountType={newbladesCountType}
        newbladesCountCurrentMonth={newbladesCountCurrentMonth}
        newBladesCurrentMonthType={newBladesCurrentMonthType}
        setInput={setInput}
        searchResult={searchResult}
        openSearchResults={openSearchResults}
        setOpenSearchResults={setOpenSearchResults}
        input={input}
      />
    </div>
  );
}
